### ISSUE TITLE
Support expansion of arbitrary environment variables

### ISSUE THREAD

**Issue by grayside** [consolidation/config#12]
While the existing environment configuration has application-namespaced environment variables with known configuration keys covered, support for arbitrary environment variables is lacking.

Such support would greatly facilitate some basic dynamic functionality, and fit well with (docker) container paradigms such as: have present only the code and config you need, apply "contextual/environmental" runtime config via env vars. I currently use this to make dynamic Drush uri configuration in site aliases, amongst other cases.

As a starting place for discussion, I propose:

```
${env.raw.MY_ARBITRARY_VAR}
```

I am not sure where to get started but with some guidance am happy to submit a PR.

**Comment by greg-1-anderson** [comment]
Expansion of `${foo}` is done via the [yaml-expander](https://github.com/grasmash/yaml-expander) project. See https://github.com/grasmash/yaml-expander/issues/9

**Comment by grayside** [comment]
Now that https://github.com/grasmash/yaml-expander/releases/tag/1.4.0 has been released with this functionality, is it available here?

**Comment by greg-1-anderson** [comment]
Well, this works today:
```
$ BAZ=bar ./drush ev 'return \Drush\Drush::config()->get("example");'
foobarbaz
```
In this case, we have:
```
example: foo{$env.BAZ}bar
```
Now, where is that implemented?  Probably the referenced issue, namely https://github.com/grasmash/yaml-expander/commit/862fe4924e1bce39f6681abc0aea6f430effbbb9

I think.
