### ISSUE TITLE
Latest release 2.0.4 forces expander2 on annotated-command 4.2.4

### ISSUE THREAD

**Issue by gterras** [consolidation/config#52]
Hi, 

I don't know if it's expected but with 

```javascript
    // composer.json
    "require-dev": {
        "consolidation/annotated-command": "4.2.4"
    },
```

This commit https://github.com/consolidation/config/commit/1cd749a8f323c2736ff5c60ba0e7e1ca189e6d0b changes `composer install` from 

```
  - Locking consolidation/config (2.0.3)
  - Locking grasmash/expander (1.0.0)
  - Locking dflydev/dot-access-data (v1.1.0)
 ```
to 

```
  - Locking consolidation/config (2.0.4)
  - Locking grasmash/expander (2.0.0)
  - Locking dflydev/dot-access-data (v3.0.1)
```

Thanks

**Comment by greg-1-anderson** [comment]
It doesn't force grasmash/expander ^2, it allows it. You may still pin to grasmash/expander ^1 if you wish.

Is the current situation causing any problems?

**Comment by gterras** [comment]
It's not really a problem per se since you are supposed to have a composer-lock but with the given composer.json above, which contains only a reference to annotated-command 4.2.4 (I don't even know what expander is), will now load a breaking version of two other packages by default compared to what it did just before 2.0.4 release, so it might be surprising to some users who do not use anything other than annotated-command directly since they don't know what consolidation-config is (in my case env variables were empty since access-data was suddenly updated to a breaking version).

**Comment by greg-1-anderson** [comment]
dfyldev/dot-access-data is used by consolidation/config; however, clients that use consolidation/config do not have to use dot-access-data directly. It is permissible for consolidation/config to add compatibility with a new major version of a dependency in one of its own patch releases, as this would not affect clients that only use the consolidation/config api.

If a client of consolidation/config starts using the dflydev/dot-access-data library directly, then it *should* add a direct reference to that project in its `require` section, pinning the version to only allow those that are tested and known to work. If a project uses a dependency-of-a-dependency that it simply "happens" to get, then it is in danger of being exposed to a major version upgrade, or perhaps losing the library altogether if its primary dependencies all stop using it.

In the event that a mistake of this nature is made, though, it is generally pretty straightforward to correct the problem by adding the necessary dependency.

> In my case env variables were empty since access-data was suddenly updated to a breaking version

Is this bug in consolidation/config or in your code? If the former, please provide more details. If the later, you may simply pin to ^1 until you have time to find and fix the problem.

**Comment by gterras** [comment]
> If a client of consolidation/config starts using the dflydev/dot-access-data library directly, then it should add a direct reference to that project in its require section 

Thanks for your answer, as for the error it is most probably in the code (it's a collection of Robo scripts that I didn't write).
